skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
token2022_confidential_payments = "8DXYc6hMDiU9jh5QJSYVR59kkvpoJKCnLWoSUn8V1L27"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
